TRAIN:
  ENABLE: True
  DATASET: sar_rarp50
  BATCH_SIZE: 9
  EVAL_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: False
DATA:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.08, 1.0]
  TRAIN_JITTER_ASPECT_RELATIVE: [0.75, 1.3333]
AVA:
  DETECTION_SCORE_THRESH: 0.75
  FRAME_LIST_DIR: stuff_AR
  FRAME_DIR: ''
  TEST_LISTS: ["inference.csv"]
  TEST_PREDICT_BOX_LISTS: ["inference_preds.csv"]
  EXCLUSION_FILE: ""
  FULL_TEST_ON_VAL: True
MVIT:
  ZERO_DECAY_POS_CLS: False
  NUM_HEADS: 1
  EMBED_DIM: 96
  PATCH_KERNEL: (3, 7, 7)
  PATCH_STRIDE: (2, 4, 4)
  PATCH_PADDING: (1, 3, 3)
  MLP_RATIO: 4.0
  QKV_BIAS: True
  DROPOUT_RATE: 0.0
  DROPPATH_RATE: 0.2
  NORM: "layernorm"
  MODE: "conv"
  DEPTH: 16
  POOL_Q_STRIDE: [[1, 1, 2, 2], [3, 1, 2, 2], [14, 1, 2, 2]]
  DIM_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [14, 2.0]]
  POOL_KV_STRIDE_ADAPTIVE: [1, 8, 8]
  POOL_KVQ_KERNEL: [3, 3, 3]
  SEP_POS_EMBED: True
  CLS_EMBED_ON: True
  FREEZE_PATCH: False
DETECTION:
  ENABLE: True
  ALIGNED: True
  ROI_XFORM_RESOLUTION: 3
AUG:
  ENABLE: False
  COLOR_JITTER: 0.4
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
  INTERPOLATION: bicubic
  NUM_SAMPLE: 1
  RE_MODE: pixel
  RE_COUNT: 1
  RE_SPLIT: False
MIXUP:
  ENABLE: False
  LABEL_SMOOTH_VALUE: 0.1
  ALPHA: 0.8
  CUTMIX_ALPHA: 1.0
  PROB: 1.0
  SWITCH_PROB: 0.5
MODEL:
  ARCH: mvit
  MODEL_NAME: MViT
  LOSS_FUNC: soft_cross_entropy
  DROPOUT_RATE: 0.5
TASKS:
  TASKS:  ["gestures","tools"]
  NUM_CLASSES: [8,10]
  HEAD_ACT:  ["softmax","softmax"]  
TEST:
  ENABLE: True
  DATASET: sar_rarp50
  BATCH_SIZE: 9
DATA_LOADER:
  NUM_WORKERS: 10
  PIN_MEMORY: True
FASTER:
  ENABLE: True
  FEATURES_VAL: stuff_MS/features_fold1.pth
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
LOG_PERIOD: 10
OUTPUT_DIR: .